name: Curl POST Request to ents24.com

on:
  push:
    branches: [ main, master ]

jobs:
  curl-request:
    runs-on: ubuntu-latest

    steps:
    - name: 'Execute curl POST Request'
      uses: wei/curl@master
      with:
        args: -X POST http://codechallenge.ents24.com/${{ github.sha }}