name: Curl POST Request to ents24.com

on:
  push:
    branches: [ dev ]

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
    - name: 'Show Commit Hash'
      run: echo "The commit hash that triggered this action is ${{ github.sha }}" 
    
    - name: 'Execute curl POST Request'
      uses: wei/curl@master
      with:
        args: -X POST http://codechallenge.ents24.com/${{ github.sha }}